### ISSUE TITLE
Onboarding - Trial length incorrect

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#138]
Trial length should be 2 weeks (Eng and Esp modes)

<img width="400" alt="Screenshot 2024-01-23 at 9 55 52 AM copy" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/cadc7da5-e77a-4f0a-a19f-674d8e73087b">

**Comment by jonathan-chin** [comment]
@mariedr this is being updated by @amak-code in her current sprint.

**Comment by Beck-bili** [comment]
Reopening this because the Spanish setup still shows 3 weeks. (English is fixed though!) 
<img width="631" alt="Screenshot 2024-01-31 at 8 48 36 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/fee7e41a-865f-4aeb-a5ef-f853212d2d6d">
<img width="638" alt="Screenshot 2024-01-31 at 8 48 27 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/9d80fc74-77e6-4372-bed6-26d51dcf403c">
